# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/cirruslabs/softnet"
  url "https://github.com/cirruslabs/softnet/releases/download/0.19.0/softnet.tar.gz"
  sha256 "1612e1296834aae0b6389650c7c5190add1ee8d71474e328691e67679ecda53c"

  define_method(:install) do
    bin.install "softnet"
  end

  depends_on macos: :sequoia

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end

  test do
    system bin/"softnet", "--help"
  end
end
